name: Python Scripts Execution

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama en la que quieres que se ejecute tu acción
  pull_request:
    branches:
      - main  # Cambia 'main' por la rama en la que quieres que se ejecute tu acción

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Especifica la versión de Python que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de que 'requirements.txt' esté en tu repositorio

    - name: Execute scrape.py
      run: python scrap.py  # Ejecuta scrape.py

    - name: Execute app.py
      run: python app.py  # Ejecuta app.py
